In [1]:
#Numpy - Array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10 , (3,4))

In [4]:
arr

array([[5, 2, 9, 4],
       [5, 7, 8, 2],
       [9, 3, 6, 3]])

In [5]:
arr.reshape(2,6)

array([[5, 2, 9, 4, 5, 7],
       [8, 2, 9, 3, 6, 3]])

In [7]:
arr.reshape(2,-2423456)

array([[5, 2, 9, 4, 5, 7],
       [8, 2, 9, 3, 6, 3]])

In [8]:
arr.T

array([[5, 5, 9],
       [2, 7, 3],
       [9, 8, 6],
       [4, 2, 3]])

In [9]:
arr.flatten()

array([5, 2, 9, 4, 5, 7, 8, 2, 9, 3, 6, 3])

In [10]:
arr1 = np.array([1,2,3,4,5])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [15]:
arr

array([[5, 2, 9, 4],
       [5, 7, 8, 2],
       [9, 3, 6, 3]])

In [16]:
np.squeeze(arr)

array([[5, 2, 9, 4],
       [5, 7, 8, 2],
       [9, 3, 6, 3]])

In [17]:
data= np.array([[1] , [2] , [3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [21]:
np.squeeze(data)

array([1, 2, 3])

In [22]:
arr1

array([1, 2, 3, 4, 5])

In [23]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [24]:
np.roll(arr1, 2)

array([4, 5, 1, 2, 3])

In [25]:
arr1

array([1, 2, 3, 4, 5])

In [26]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [27]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
# Numpy - Binary Operators.

In [29]:
arr1 = np.random.randint(1,10 , (3,4))

In [30]:
arr2 = np.random.randint(1,10 , (3,4))

In [31]:
arr1

array([[3, 5, 1, 9],
       [2, 4, 7, 9],
       [3, 6, 7, 3]])

In [32]:
arr2

array([[6, 7, 1, 1],
       [6, 6, 3, 5],
       [3, 4, 1, 8]])

In [33]:
arr1 +arr2

array([[ 9, 12,  2, 10],
       [ 8, 10, 10, 14],
       [ 6, 10,  8, 11]])

In [34]:
arr1*arr2

array([[18, 35,  1,  9],
       [12, 24, 21, 45],
       [ 9, 24,  7, 24]])

In [35]:
arr1/arr2

array([[0.5       , 0.71428571, 1.        , 9.        ],
       [0.33333333, 0.66666667, 2.33333333, 1.8       ],
       [1.        , 1.5       , 7.        , 0.375     ]])

In [36]:
arr1-arr2

array([[-3, -2,  0,  8],
       [-4, -2,  4,  4],
       [ 0,  2,  6, -5]])

In [37]:
arr1%arr2

array([[3, 5, 0, 0],
       [2, 4, 1, 4],
       [0, 2, 0, 3]])

In [38]:
arr1 ** arr2

array([[  729, 78125,     1,     9],
       [   64,  4096,   343, 59049],
       [   27,  1296,     7,  6561]])

In [39]:
arr1 & arr2

array([[2, 5, 1, 1],
       [2, 4, 3, 1],
       [3, 4, 1, 0]])

In [40]:
arr1

array([[3, 5, 1, 9],
       [2, 4, 7, 9],
       [3, 6, 7, 3]])

In [41]:
arr2

array([[6, 7, 1, 1],
       [6, 6, 3, 5],
       [3, 4, 1, 8]])

In [42]:
-arr1

array([[-3, -5, -1, -9],
       [-2, -4, -7, -9],
       [-3, -6, -7, -3]])

In [43]:
arr|arr2

array([[ 7,  7,  9,  5],
       [ 7,  7, 11,  7],
       [11,  7,  7, 11]])

In [44]:
#Numpy  - String Functions.

In [45]:
arr = np.array(['Lokesh','Mendke'])

In [46]:
arr

array(['Lokesh', 'Mendke'], dtype='<U6')

In [47]:
np.char.upper(arr)

array(['LOKESH', 'MENDKE'], dtype='<U6')

In [48]:
np.char.title(arr)

array(['Lokesh', 'Mendke'], dtype='<U6')

In [49]:
np.char.capitalize(arr)

array(['Lokesh', 'Mendke'], dtype='<U6')

In [50]:
#Numpy - Mathematial Functions.

In [51]:
arr1

array([[3, 5, 1, 9],
       [2, 4, 7, 9],
       [3, 6, 7, 3]])

In [52]:
np.sin(arr1)

array([[ 0.14112001, -0.95892427,  0.84147098,  0.41211849],
       [ 0.90929743, -0.7568025 ,  0.6569866 ,  0.41211849],
       [ 0.14112001, -0.2794155 ,  0.6569866 ,  0.14112001]])

In [53]:
np.cos(arr1)

array([[-0.9899925 ,  0.28366219,  0.54030231, -0.91113026],
       [-0.41614684, -0.65364362,  0.75390225, -0.91113026],
       [-0.9899925 ,  0.96017029,  0.75390225, -0.9899925 ]])

In [54]:
np.tanh(arr1)

array([[0.99505475, 0.9999092 , 0.76159416, 0.99999997],
       [0.96402758, 0.9993293 , 0.99999834, 0.99999997],
       [0.99505475, 0.99998771, 0.99999834, 0.99505475]])

In [55]:
np.exp(arr1)

array([[2.00855369e+01, 1.48413159e+02, 2.71828183e+00, 8.10308393e+03],
       [7.38905610e+00, 5.45981500e+01, 1.09663316e+03, 8.10308393e+03],
       [2.00855369e+01, 4.03428793e+02, 1.09663316e+03, 2.00855369e+01]])

In [56]:
np.sqrt(arr1)

array([[1.73205081, 2.23606798, 1.        , 3.        ],
       [1.41421356, 2.        , 2.64575131, 3.        ],
       [1.73205081, 2.44948974, 2.64575131, 1.73205081]])

In [57]:
np.power(arr1,2)

array([[ 9, 25,  1, 81],
       [ 4, 16, 49, 81],
       [ 9, 36, 49,  9]])

In [58]:
np.mean(arr1)

4.916666666666667

In [59]:
np.median(arr1)

4.5

In [60]:
np.std(arr1)

2.5644470922381863

In [61]:
np.var(arr1)

6.576388888888889

In [ ]:
np.min(ar1)