In [2]:
import numpy as np

In [7]:
l = [ 1,2,3,4]

In [8]:
ar = np.array(l)

In [9]:
ar

array([1, 2, 3, 4])

In [11]:
type(ar)

numpy.ndarray

In [12]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [13]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [14]:
a = [2,3,4]

In [16]:
np.asanyarray(a)

array([2, 3, 4])

In [17]:
b = np.matrix(l)

In [18]:
b

matrix([[1, 2, 3, 4]])

In [19]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [20]:
a  = np.array(l)

In [21]:
a

array([1, 2, 3, 4])

In [22]:
c = a

In [23]:
c

array([1, 2, 3, 4])

In [25]:
c[0]=100

In [26]:
c

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
d = np.copy(a)

In [29]:
d

array([100,   2,   3,   4])

In [30]:
a


array([100,   2,   3,   4])

In [31]:
a[1]=400

In [32]:
a

array([100, 400,   3,   4])

In [34]:
np.fromfunction(lambda i ,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i ,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [37]:
iterable = (i*i for i in range(5))

In [38]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
np.fromstring('234 456', sep = ' ')

array([234., 456.])

In [42]:
np.fromstring('234,456', sep = ',')

array([234., 456.])

In [43]:
# Numpy - Data Types.

In [44]:
l = [2,3,4,5,6]

In [45]:
ar = np.array(l)

In [46]:
ar.ndim

1

In [49]:
ar2 = np.array ([[2,3,4,5],[1,6,7,8]])

In [50]:
ar2

array([[2, 3, 4, 5],
       [1, 6, 7, 8]])

In [51]:
ar2.ndim

2

In [52]:
ar.size

5

In [53]:
ar2.size

8

In [54]:
ar.shape

(5,)

In [55]:
ar2.shape

(2, 4)

In [56]:
ar2.dtype

dtype('int64')

In [62]:
ar22 = np.array([(1.8,3,5,7),(2,4,6,8)])

In [63]:
ar22

array([[1.8, 3. , 5. , 7. ],
       [2. , 4. , 6. , 8. ]])

In [64]:
ar22.dtype

dtype('float64')

In [66]:
list(range(5))

[0, 1, 2, 3, 4]

In [73]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [70]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [71]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [72]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [74]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [76]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [80]:
ar4 = np.zeros((3,4,2,3))

In [82]:
ar4.ndim

4

In [83]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [84]:
np.ones(4)

array([1., 1., 1., 1.])

In [87]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [90]:
on = np.ones((2,3,2))

In [91]:
on +5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [92]:
on *5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [94]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [96]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.linspace(2,4 ,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [100]:
np.logspace(2,5, 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [102]:
arr = np.random.randn(3,4)

In [103]:
import pandas as pd

In [105]:
pd.DataFrame(arr)

0         1         2         3
0  0.982097 -0.366622  1.867451 -0.166836
1 -1.093753  0.092496 -0.381081 -0.553629
2  0.216687 -0.195849 -0.423819 -1.043687

In [106]:
np.random.rand(3,4)

array([[0.26821159, 0.83846627, 0.8537526 , 0.1245332 ],
       [0.36653379, 0.84535438, 0.4226711 , 0.16959915],
       [0.46615417, 0.98778943, 0.59146931, 0.4932622 ]])

In [107]:
np.random.randint(1,110, (3,4))

array([[53, 37, 11, 15],
       [17,  7, 30, 76],
       [23,  7, 29, 56]])

In [109]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('test.csv')

In [110]:
arr =np.random.rand(3,4)

In [111]:
arr

array([[0.79588298, 0.58040501, 0.76335608, 0.05544637],
       [0.31253113, 0.79179917, 0.6690999 , 0.22066187],
       [0.8660721 , 0.48192024, 0.58225176, 0.16973303]])

In [114]:
arr.reshape(6,-1)

array([[0.79588298, 0.58040501],
       [0.76335608, 0.05544637],
       [0.31253113, 0.79179917],
       [0.6690999 , 0.22066187],
       [0.8660721 , 0.48192024],
       [0.58225176, 0.16973303]])

In [116]:
arr1 = arr.reshape(6,-1345678)

In [118]:
arr1

array([[0.79588298, 0.58040501],
       [0.76335608, 0.05544637],
       [0.31253113, 0.79179917],
       [0.6690999 , 0.22066187],
       [0.8660721 , 0.48192024],
       [0.58225176, 0.16973303]])

In [119]:
arr1[1][1]

0.055446368370341004

In [121]:
arr1[2:5]

array([[0.31253113, 0.79179917],
       [0.6690999 , 0.22066187],
       [0.8660721 , 0.48192024]])

In [122]:
arr1[2:5,1]

array([0.79179917, 0.22066187, 0.48192024])

In [125]:
arr = np.random.randint(1,100,(5,5))

In [126]:
arr

array([[72, 87, 17, 50, 14],
       [36, 87, 74,  9, 82],
       [45, 79, 55,  3, 31],
       [45, 40, 54,  7, 88],
       [84, 57, 46, 36, 54]])

In [127]:
arr >50

array([[ True,  True, False, False, False],
       [False,  True,  True, False,  True],
       [False,  True,  True, False, False],
       [False, False,  True, False,  True],
       [ True,  True, False, False,  True]])

In [128]:
arr[arr >50]

array([72, 87, 87, 74, 82, 79, 55, 54, 88, 84, 57, 54])

In [129]:
arr

array([[72, 87, 17, 50, 14],
       [36, 87, 74,  9, 82],
       [45, 79, 55,  3, 31],
       [45, 40, 54,  7, 88],
       [84, 57, 46, 36, 54]])

In [131]:
arr[2:4,[1,2]]

array([[79, 55],
       [40, 54]])

In [132]:
arr[0][0] = 5000

In [133]:
arr

array([[5000,   87,   17,   50,   14],
       [  36,   87,   74,    9,   82],
       [  45,   79,   55,    3,   31],
       [  45,   40,   54,    7,   88],
       [  84,   57,   46,   36,   54]])

In [134]:
arr1

array([[0.79588298, 0.58040501],
       [0.76335608, 0.05544637],
       [0.31253113, 0.79179917],
       [0.6690999 , 0.22066187],
       [0.8660721 , 0.48192024],
       [0.58225176, 0.16973303]])

In [137]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [138]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [139]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 2, 2]])

In [140]:
arr1+arr2

array([[3, 4, 4],
       [2, 3, 2],
       [2, 4, 3]])

In [141]:
arr1 - arr2

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [142]:
arr1 / arr2

array([[0.5, 1. , 1. ],
       [1. , 0.5, 1. ],
       [1. , 1. , 0.5]])

In [143]:
arr1 * arr2

array([[2, 4, 4],
       [1, 2, 1],
       [1, 4, 2]])

In [144]:
arr1@arr2

array([[ 6, 10,  8],
       [ 4,  6,  5],
       [ 5,  8,  6]])

In [145]:
arr1 / 0

/tmp/ipykernel_103/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [146]:
arr1 +100

array([[101, 102, 102],
       [101, 101, 101],
       [101, 102, 101]])

In [147]:
arr1 **2

array([[1, 4, 4],
       [1, 1, 1],
       [1, 4, 1]])

In [148]:
# Numpy - Broadcasting.

In [151]:
arr = np.zeros((4,4))

In [152]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [153]:
row = np.array([1,2,3,4])

In [154]:
row

array([1, 2, 3, 4])

In [155]:
arr +row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [157]:
row.T

array([1, 2, 3, 4])

In [158]:
col = np.array([[1,2,3,4]])

In [159]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [160]:
col

array([[1, 2, 3, 4]])

In [161]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [162]:
np.random.randint(1,4 ,(3,4))

array([[2, 1, 1, 3],
       [3, 1, 3, 2],
       [3, 3, 1, 2]])

In [163]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [165]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [168]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [169]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.     ],
       [0.     , 0.30103, 0.     ]])